/** Pipelines PDF — funil de leads e negócios por mercado. */

export const FUNIL_LEAD_ETAPAS = [
  { slug: "novo", label: "Novo", ordem: 1, cor: "#6B7280" },
  { slug: "em_atendimento", label: "Em atendimento", ordem: 2, cor: "#C9A24A" },
  { slug: "aguardando_resposta", label: "Aguardando resposta", ordem: 3, cor: "#E0B86A" },
  { slug: "qualificando", label: "Qualificando", ordem: 4, cor: "#D6A129" },
  { slug: "encaminhado", label: "Encaminhado", ordem: 5, cor: "#F59E0B" },
  { slug: "convertido_negocio", label: "Convertido em negócio", ordem: 6, cor: "#22C55E" },
  { slug: "perdido", label: "Perdido", ordem: 7, cor: "#EF4444" },
  { slug: "spam_invalido", label: "Spam ou inválido", ordem: 8, cor: "#9CA3AF" },
] as const;

export type FunilLeadSlug = (typeof FUNIL_LEAD_ETAPAS)[number]["slug"];

export const MOTIVOS_PERDA = [
  "sem_resposta",
  "sem_orcamento",
  "fora_da_regiao",
  "sem_perfil",
  "dados_invalidos",
  "nao_quer_agora",
  "escolheu_concorrente",
  "preco_incompativel",
  "prazo_incompativel",
  "escopo_incompativel",
  "falta_documentacao",
  "lead_duplicado",
  "atendimento_recusado",
  "outro",
] as const;

export const MOTIVOS_PERDA_LABEL: Record<string, string> = {
  sem_resposta: "Sem resposta",
  sem_orcamento: "Sem orçamento",
  fora_da_regiao: "Fora da região",
  sem_perfil: "Sem perfil",
  dados_invalidos: "Dados inválidos",
  nao_quer_agora: "Não quer avançar agora",
  escolheu_concorrente: "Escolheu concorrente",
  preco_incompativel: "Preço incompatível",
  prazo_incompativel: "Prazo incompatível",
  escopo_incompativel: "Escopo incompatível",
  falta_documentacao: "Falta de documentação",
  lead_duplicado: "Lead duplicado",
  atendimento_recusado: "Atendimento recusado",
  outro: "Outro",
};

export const MERCADOS_NEGOCIO = [
  { slug: "imobiliario", label: "Imobiliário", prefixo: "IMB" },
  { slug: "arquitetura", label: "Arquitetura", prefixo: "ARQ" },
  { slug: "obra_reforma", label: "Obra e reforma", prefixo: "RFM" },
  { slug: "engenharia", label: "Engenharia civil", prefixo: "ENG" },
  { slug: "marcenaria_moveis", label: "Marcenaria e móveis", prefixo: "MRC" },
  { slug: "servicos", label: "Serviços", prefixo: "SRV" },
  { slug: "produtos_materiais", label: "Produtos e materiais", prefixo: "PRO" },
  { slug: "fornecedor_homologacao", label: "Fornecedor em homologação", prefixo: "FOR" },
] as const;

export const ETAPAS_NEGOCIO_POR_MERCADO: Record<string, { slug: string; label: string }[]> = {
  imobiliario: [
    { slug: "novo_negocio", label: "Novo negócio" },
    { slug: "contato_validado", label: "Contato validado" },
    { slug: "encaminhado_corretor", label: "Encaminhado ao corretor" },
    { slug: "atendimento_corretor", label: "Em atendimento pelo corretor" },
    { slug: "imovel_selecionado_captado", label: "Imóvel selecionado ou captado" },
    { slug: "visita_agendada", label: "Visita ou avaliação agendada" },
    { slug: "proposta_negociacao", label: "Proposta em negociação" },
    { slug: "documentacao", label: "Documentação em andamento" },
    { slug: "fechado_ganho", label: "Fechado ganho" },
    { slug: "fechado_perdido", label: "Fechado perdido" },
  ],
  arquitetura: [
    { slug: "novo_negocio", label: "Novo negócio" },
    { slug: "contato_validado", label: "Contato validado" },
    { slug: "briefing_inicial", label: "Briefing inicial" },
    { slug: "reuniao_agendada", label: "Reunião agendada" },
    { slug: "briefing_completo", label: "Briefing completo" },
    { slug: "proposta_elaboracao", label: "Proposta em elaboração" },
    { slug: "proposta_enviada", label: "Proposta enviada" },
    { slug: "negociacao", label: "Negociação" },
    { slug: "contrato_aprovado", label: "Contrato aprovado" },
    { slug: "fechado_ganho", label: "Fechado ganho" },
    { slug: "fechado_perdido", label: "Fechado perdido" },
  ],
  obra_reforma: [
    { slug: "novo_negocio", label: "Novo negócio" },
    { slug: "contato_validado", label: "Contato validado" },
    { slug: "escopo_inicial", label: "Escopo inicial recebido" },
    { slug: "visita_agendada", label: "Visita técnica agendada" },
    { slug: "levantamento", label: "Levantamento realizado" },
    { slug: "orcamento_elaboracao", label: "Orçamento em elaboração" },
    { slug: "proposta_enviada", label: "Proposta enviada" },
    { slug: "negociacao", label: "Negociação" },
    { slug: "contrato_aprovado", label: "Contrato aprovado" },
    { slug: "obra_criada", label: "Obra criada" },
    { slug: "fechado_perdido", label: "Fechado perdido" },
  ],
  engenharia: [
    { slug: "novo_negocio", label: "Novo negócio" },
    { slug: "contato_validado", label: "Contato validado" },
    { slug: "demanda_entendida", label: "Demanda técnica entendida" },
    { slug: "documentos_solicitados", label: "Documentos solicitados" },
    { slug: "analise_tecnica", label: "Análise técnica" },
    { slug: "visita_tecnica", label: "Visita técnica, se necessário" },
    { slug: "proposta_tecnica", label: "Proposta técnica" },
    { slug: "proposta_comercial", label: "Proposta comercial" },
    { slug: "negociacao", label: "Negociação" },
    { slug: "contrato_aprovado", label: "Contrato aprovado" },
    { slug: "projeto_obra_criado", label: "Projeto ou obra criado" },
    { slug: "fechado_perdido", label: "Fechado perdido" },
  ],
  marcenaria_moveis: [
    { slug: "novo_negocio", label: "Novo negócio" },
    { slug: "contato_validado", label: "Contato validado" },
    { slug: "ambiente_identificado", label: "Ambiente identificado" },
    { slug: "medidas_solicitadas", label: "Medidas ou projeto solicitado" },
    { slug: "fornecedor_sugerido", label: "Fornecedor sugerido" },
    { slug: "cotacao", label: "Cotação em andamento" },
    { slug: "proposta_enviada", label: "Proposta enviada" },
    { slug: "negociacao", label: "Negociação" },
    { slug: "pedido_aprovado", label: "Pedido aprovado" },
    { slug: "producao_entrega", label: "Produção ou entrega criada" },
    { slug: "fechado_perdido", label: "Fechado perdido" },
  ],
  servicos: [
    { slug: "novo_negocio", label: "Novo negócio" },
    { slug: "contato_validado", label: "Contato validado" },
    { slug: "servico_identificado", label: "Serviço identificado" },
    { slug: "fotos_solicitadas", label: "Fotos ou informações solicitadas" },
    { slug: "fornecedor_sugerido", label: "Fornecedor sugerido" },
    { slug: "cotacao", label: "Cotação em andamento" },
    { slug: "proposta_enviada", label: "Proposta enviada" },
    { slug: "execucao_agendada", label: "Execução agendada" },
    { slug: "servico_fechado", label: "Serviço fechado" },
    { slug: "fechado_perdido", label: "Fechado perdido" },
  ],
  produtos_materiais: [
    { slug: "novo_negocio", label: "Novo negócio" },
    { slug: "contato_validado", label: "Contato validado" },
    { slug: "produto_identificado", label: "Produto identificado" },
    { slug: "especificacao_recebida", label: "Quantidade ou especificação recebida" },
    { slug: "fornecedor_sugerido", label: "Fornecedor sugerido" },
    { slug: "cotacao", label: "Cotação em andamento" },
    { slug: "proposta_enviada", label: "Proposta enviada" },
    { slug: "pedido_aprovado", label: "Pedido aprovado" },
    { slug: "entrega_andamento", label: "Entrega em andamento" },
    { slug: "fechado_perdido", label: "Fechado perdido" },
  ],
  fornecedor_homologacao: [
    { slug: "cadastro_recebido", label: "Cadastro recebido" },
    { slug: "dados_validados", label: "Dados mínimos validados" },
    { slug: "documentos_solicitados", label: "Documentos solicitados" },
    { slug: "documentacao_pendente", label: "Documentação pendente" },
    { slug: "em_analise", label: "Em análise" },
    { slug: "entrevista", label: "Entrevista ou reunião" },
    { slug: "avaliacao_tecnica", label: "Avaliação técnica" },
    { slug: "avaliacao_comercial", label: "Avaliação comercial" },
    { slug: "aprovado", label: "Aprovado" },
    { slug: "homologado", label: "Homologado" },
    { slug: "reprovado", label: "Reprovado" },
    { slug: "suspenso", label: "Suspenso" },
  ],
};

export const LEGADO_ESTAGIO_PARA_FUNIL: Record<string, FunilLeadSlug> = {
  novo: "novo",
  qualificando: "qualificando",
  qualificado: "qualificando",
  proposta: "encaminhado",
  negociando: "em_atendimento",
  fechamento: "encaminhado",
  ganho: "convertido_negocio",
  perdido: "perdido",
};

export const FUNIL_PARA_LEGADO_ESTAGIO: Record<FunilLeadSlug, string> = {
  novo: "novo",
  em_atendimento: "negociando",
  aguardando_resposta: "qualificando",
  qualificando: "qualificando",
  encaminhado: "proposta",
  convertido_negocio: "ganho",
  perdido: "perdido",
  spam_invalido: "perdido",
};
